//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyTitle("Habitat.Server.AdminWebConsole.Tests")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Pro Teck")]
[assembly: AssemblyProduct("Habitat.Server.AdminWebConsole.Tests")]
[assembly: AssemblyCopyright("Copyright © Pro Teck Valuation Services 2014")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0+2014.124.45271")]

// Generated by the MSBuild WriteCodeFragment class on 5/4/2014 12:34:31 PM.

